### ISSUE TITLE
[6600 GPU] Ventura Support

### ISSUE THREAD

**Issue by dreamwhite** [perez987/macOS-12-13-on-Z390-with-OpenCore#1]
Hi, as far as I can tell, SSDT-BRG0 may solve issues since it defines missing `pci-bridge`. Send me an IOReg dump on Telegram (my contact [here](https://t.me/dreamwhitedev)) as it contains SMBIOS serial numbers, as I hope you don't wanna spread publicly your data

**Comment by perez987** [comment]
@dreamwhite 
Good morning.
Are you talking about 6600 and Ventura with iMacPro or MacPro SMBIOS? Black screen if Henbury patch not added?
I’lI get the IOReg with the patch applied, right?
Thanks.

**Comment by dreamwhite** [comment]
Good morning, yeah, theoretically SMBIOS doesn't matter, so you just need to fix pci-bridges. Once you get the IOReg send it on my Telegram so I can send you the right SSDT-BRG0, properly configured for your PCI path

**Comment by perez987** [comment]
Ok, wait I,m out.

**Comment by perez987** [comment]
@dreamwhite 
Ok, I've tried SSDT-BRG0 with iMac19,1 and MacPro7,1 SMBIOS.

iMac19,1 runs fine, I don't see any differences except the different path in IOReg. 
`PCI0@0/PEG0@1/PEGP@0/BRG0@0/GFX0@0`

But MacPro7,1 can boot now Ventura without the Henbury patch.
As I say in the README, iMac doesn't need Henbury patch in Ventura but MacPro and iMacPro both do, to not have black screen when reaching the Desktop. With SSDT-BRG0 the patch is not needed.

Henbury patch drops down GeekBench 5 Metal scores. With SSDT-BRG0 scores are the same as on iMac without Henbury patch. So, your SSDT-BRG0 seems to be a better solution to avoid black screen on Ventura when using SMBIOS that lack iGPU.

Thanks!

**Comment by dreamwhite** [comment]
Hi wonderful! Hope you enjoy this SSDT :D

**Comment by perez987** [comment]
Yes, I'll add a comment in the README file. Thanks again.
