### ISSUE TITLE
Black screen when boot window from OC

### ISSUE THREAD

**Issue by taida2203** [perez987/macOS-12-13-on-Z390-with-OpenCore#2]
I added an additional M2 SSD to boot window but when I'm trying to select WIN from OC, it just restart and showing black screen instead of loading window 10. 
I believe there are some mapping on ACPI that make window crash. I tried to boot WIN alone and it worked.
@perez987 can you give me some advice ?

I'm using  config-12-imac-amd.plist

**Comment by perez987** [comment]
@taida2203
Good afternoon. 
How is the OpenCore setting to boot Windows? Custom entry created by you or automatically detected by OpenCore?
Do at least once ResetNVRAM at boot, does it fixes something?

**Comment by perez987** [comment]
@taida2203 
There is a mod for OpenCore, [OpenCore_NO_ACPI_Build ](https://github.com/wjz304/OpenCore_NO_ACPI_Build)by @wjz304. This mod doesn't pass OpenCore ACPI values to other OSes.
Try the attached EFI (made with this OC mod) but rename EFI-taida2203 to EFi and do ResetNVRAM the first time you boot it.
Tell me if Windows boots well from OpenCore with this build.

[EFI-taida2203.zip](https://github.com/perez987/macOS-12-13-on-Z390-with-OpenCore/files/10200877/EFI-taida2203.zip)

**Comment by taida2203** [comment]
@perez987 I tried [EFI-taida2203.zip](https://github.com/perez987/macOS-12-13-on-Z390-with-OpenCore/files/10200877/EFI-taida2203.zip) but it still same when loading windows. If I tried to boot with mac then screen have random flicking or random restart.
Actually your EFI work smoothly but I'm trying to dual boot windows base on your EFI @perez987 . Do you have any suggestion on this ? Can we made some "if .. else .." on this case to determine windows / mac ?

**Comment by perez987** [comment]
@taida2203 
The OC mod is made specifically to not pass any ACPI table to Windows when booting from OpenCore. 
In addition to this, SSDTs included in my EFI have methods to detect if we are on macOS to not pass ACPI data to Windows. The OC mod only makes this 
more strictly.
My config file also has settings to not pass SMBIOS data to Windows. 
I don’t know what else to try.

**Comment by taida2203** [comment]
@perez987 my window is located on different nvme drive and it works fine when boot directly. I'll try this [OpenCore_NO_ACPI_Build ](https://github.com/wjz304/OpenCore_NO_ACPI_Build)by @wjz304 first and check if can boot to windows from OC or not

**Comment by wjz304** [comment]
You can take a look at this link
[OpenCore PostInstall](https://github.com/dortania/OpenCore-Post-Install/blob/12bc1dce7e644eca44a46ca5292be24b4c0e3338/multiboot/bootcamp.md#booting-windows-error-ocb-startimage-failed---already-started)

**Comment by perez987** [comment]
Thanks @wjz304 the taida2203 issue is not clear for me. If using your mod the issue is gone, it would be clearly ACPI data passed to Windows. Waiting for the comment of @taida2203

**Comment by perez987** [comment]
Still waiting for @taida2203 commenting if the issue has been fixed.
