### ISSUE TITLE
Help with install Intel Core i5-10400

### ISSUE THREAD

**Issue by jzjz2000** [perez987/macOS-12-13-on-Z390-with-OpenCore#3]
Hi there..
I am planning to use your config.plist for my new Ventura build.
I have slightly different hardware:
CPU: intel core i5-10400

MB: GIGABYTE Z490 AORUS Elite AC (Intel LGA1200/Z490/ATX/2xM.2 Thermal Guard/Realtek ALC1200/SATA 6Gb/s/USB 3.2 Gen 2/Intel 802.11ac/2.5 GbE LAN/RGB Fusion/Gaming Motherboard)

GPU: XFX Speedster SWFT 210 Radeon RX 6600 CORE Gaming Graphics Card with 8GB GDDR6 HDMI 3xDP, AMD RDNA 2 RX-66XL8LFDQ

Networking: fenvi T919 PCI-E WiFi Adapter Continuity Handoff BCM94360CD WiFi Card for macOS Windows 7 8 10 11 Native Airport BT4.0 1750Mbps Dual Band 802.11ac Beamforming+ WLAN Plug and Play Cataline Mojave OS X

I know it is better to build your own config.plst , but I would like to save some time. :-)
Do you think yours would work enough to install the OS? and after setup would it run ok?
I am planning to use your 0.9.0 open core config-13-imac-amd.plist: iMac19,1 + dGPU AMD + iGPU enabled in BIOS.
Since I have a dGPU 6000 and an Intel Cpu with iGPU 630, I think this seems best? What do you think?
Also open core guide says use smbios 20,1 or 20,2 for comet lake cpu's, would that be a better smbios than the 19.1 you are using?

Thanks for any help

**Comment by perez987** [comment]
@jzjz2000 
Im not at home. I’ll answer to you later.

**Comment by perez987** [comment]
@jzjz2000 
You have an Intel 630 Comet Lake that can use the same configuration as the Coffee Lake model (mine). Most likely the same code that works for the 9th gen. (Coffee Lake R) is valid for the 10th (Comet Lake). In [Dortania's guide](https://github.com/dortania/OpenCore-Install-Guide/blob/b3d18f45e81fab28440e2ab864d5ca8bb49d1e9e/config.plist/comet-lake.md) for Comet Lake they have the same AAPL,ig-platform-id as Coffee Lake.
This is valid for iMac 20.x SMBIOS (actually more adapted to Z490 and 10th gen. than iMac 19.x).

The RX 6600 dGPU should work fine as of macOS 12.1. You already know that it only needs `agdpmod=pikera` in boot args.

There are 2 options for SMBIOS:
- iMac20,2: iGPU enabled in BIOS and AMD as main card, wirh headless mode code for the iGPU in config.plist.
- iMacPro1,1: iGPU disabled in BIOS and no code for it in config.plist.

Both really work well. The main difference is DRM: on some systems with iMac (not all) Netflix and other services don't work in Safari (they do work in Chrome) and Apple TV doesn't work either, whereas with iMacPro everything related to DRM usually works fine.
Try both SMBIOS and choose the one you like best.

I think you can test my EFI with OpenCore 0.9.0. Comment here if it works well or if you have any issues.

**Comment by jzjz2000** [comment]
Thank you for the quick reply. I will be getting the last parts for assembly later today, hopefully.
I will try the iMac 20,2 first, I have used a dGpu 580x Polaris series in the past on a different setup. It worked fine but I would like to test if there is any advantage to using dGpu and iGpu together, so SMBIOS 20,2 sounds interesting. So all I really need to add to your config.plist is my serial and and the <agdpmod=pikera>  boot args?
I will try the opencore configurator to add those values. I will make a USBflash drive installer for both smbios’s and test them both out. I will let you know if it works.

Thanks again for your help and working on this project.

**Comment by perez987** [comment]
@jzjz2000 
Yes, to use a 5000 or 6000 series AMD card just add the boot arg. Nothing else. Of course with Lilu and WhateverGreen.
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#amd-gpus

For the iGPU to work in headless mode as an aid in coding you have to add the appropriate code to config.plist, in my article you have it in the `Intel UHD 630 headless mode` section. The cable to the monitor comes out of the AMD card. The iGPU does not have cable to the monitor.

**Comment by jzjz2000** [comment]
Great tip I was wondering about that. Another step I’m stuck at: In your intro guide #3 is says gatekeeper should be enable with terminal command before install. How can I do this before/while installing? Or do I run in the terminal at the recovery screen before install? Or is there a checkmark on oc configurator that I’m missing? Thanks for any more help.

**Comment by jzjz2000** [comment]
Sent from my iPhoneOn Mar 10, 2023, at 3:53 PM, Axel Kristensen ***@***.***> wrote:﻿Great tip I was wondering about that.Another step I’m stuck at:In your intro guide #3 is says gatekeeper should be enable with terminal command before install. How can I do this before/while installing? Or do I run in the terminal at the recovery screen before install?Or is there a checkmark on oc configurator that I’m missing?Thanks for any more helpAxelSent from my iPhoneOn Mar 10, 2023, at 2:56 PM, Emilio P Egido ***@***.***> wrote:﻿
@jzjz2000
Yes, to use a 5000 or 6000 series AMD card just add the boot arg. Nothing else. Of course with Lilu and WhateverGreen.
https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#amd-gpus
For the iGPU to work in headless mode as an aid in coding you have to add the appropriate code to config.plist, in my article you have it in the Intel UHD 630 headless mode section. The cable to the monitor comes out of the AMD card. The iGPU does not have cable to the monitor.

**Comment by jzjz2000** [comment]
Also how do I add the code for headless mode: In oc configurator? Which section? Or do have to use plist pro editor?

**Comment by jzjz2000** [comment]
Sorry for the overload 🤓 but I’m very excited to get my new hackmac going. Would this oc configurator page work to add the headless code to?

**Comment by perez987** [comment]
@jzjz2000 
Don’t worry, I’m not overloaded 😂
I don’t have OC Configurator now, sometimes it breaks something in config.plist. PlistPro Editor is ok, free version runs fine without limitations. 
In my guide, the text for iGPU headless mode can be added as is with a simple plain text editor. The pic named `Image: iGPU as secondary card`, instead, is how you write it in PlistPro Editor.   
But why don’t get my `config-13-imac-amd.plist`, adding ROM and serial numbers for iMac20,2 and renaming it to config.plist? You already have there the headless mode. The device path to the iGPU is the same in our mobos.
Any doubt you have, upload here your config.plist to be revised.

**Comment by perez987** [comment]
@jzjz2000 
About GateKeeper, it’s enabled by default. If you want to be sure, do in Terminal:
`sudo spctl —global-enable`
Or look at the Privacy and Security preferences pane. If it’s allowed to install apps from Anywhere, GateKeeper is disabled. If it’s alowed to install apps from Apple Store or identified developers, GateKeeper is enabled. 
Recovery is not needed for this task.

**Comment by jzjz2000** [comment]
Thanks again it works great, installed and booted on the first try. 😁 Had a few quirks, mainly user error. I typed the wrong device id into config.plist, I think I’m using the wrong headless mode code not realizing that it was already correct in your config-13-imac-amd.plist which I used and changed. I will fix that tomorrow.
Question: in the bios should the iGpu be on auto or enabled? both gave me a black screen on boot. Until I disabled it. It’s probably because I typed in the wrong device ID.
Thank you so much again, you saved me alot of trial and error. If there is anything I can do to help you with any tech, I am very techy let me know, or a donation of some kind.
Thanks again, Be well.

**Comment by perez987** [comment]
@jzjz2000 
I like to teach as much as I like to learn, people teach me for free (and I'm not so techy, despite my Internet sites) and I do the same, thank you for your offer.
iMac20,1 must have iGPU Enabled in BIOS. iMacPro1,1 must have it Disabled. Forget Auto mode.
Black screen can have to do with the wrong device path in config.plist but it's a strange behaviour, with the wrong path you should see the screen fine thanks to the AMD but the iGPU would not work on encoding tasks. Either way, try with the right path as in my config.plist. If the screen goes black, there is something else we need to look at.
The cable to the monitor: type of connection? HDMI - HDMI, DisplayPort - DisplayPort, etc.

**Comment by jzjz2000** [comment]
﻿﻿﻿﻿﻿I think I got it working. I just had the wrong value in the device properties. You can see the changes I made in the 2nd try config.plist. I am attaching the before and after plist.
I think your setup uses an Intel Ethernet chip, this board uses a Realtek 2.5GB. So I can probably remove the intelmausi.kext and add a Realtek one?
I attached a couple of other pictures for give you all the info I can, sorry for glare on pics.
Also does the usb map look correct? See pic in zip.
The platform info looks very empty. I have a serial number in there but nothing else. I used oc configurator to add info except I got the serial number from the macserial app. See pic in zip. My older hackmac had alot more info.
Thanks for taking the time to help again.
I attached 2 .zip files one before changes and one after.
Axel
Ps. The .zips are to big to attach, I will send them separately.

**Comment by jzjz2000** [comment]
Sent from my iPhoneOn Mar 11, 2023, at 7:25 PM, Axel Kristensen ***@***.***> wrote:﻿﻿﻿﻿﻿﻿I think I got it working. I just had the wrong value in the device properties. You can see the changes I made in the 2nd try config.plist.I am attaching the before and after plist.-2 quirksI think your setup uses an Intel Ethernet chip, this board uses a Realtek 2.5GB.<IMG_2048.png>So I can probably remove the intelmausi.kext and add a Realtek one? I attached a couple of other pictures for give you all the info I can, sorry for glare on pics.Also does the usb map look correct?See pic in zip-The platform info looks very empty.I have a serial number in there but nothing else. I used oc configurator to add info except I got the serial number from the macserial app. See pic in zip. My older hackmac had alot more info.Thanks for taking the time to help again.I attached 2 .zip files one before changes and one after. AxelPs. The .zips are to big to attach, I will send them separately Sent from my iPhoneOn Mar 11, 2023, at 7:18 AM, Emilio P Egido ***@***.***> wrote:﻿
@jzjz2000
I like to teach as much as I like to learn, people teach me for free (and I'm not so techy, despite my Internet sites) and I do the same, thank you for your offer.
iMac20,1 must have iGPU Enabled in BIOS. iMacPro1,1 must have it Disabled. Forget Auto mode.
Black screen can have to do with the wrong device path in config.plist but it's a strange behaviour, with the wrong path you should see the screen fine thanks to the AMD but the iGPU would not work on encoding tasks. Either way, try with the right path as in my config.plist. If the screen goes black, there is something else we need to look at.
The cable to the monitor: type of connection? HDMI - HDMI, DisplayPort - DisplayPort, etc.

**Comment by perez987** [comment]
@jzjz2000 
Deleted a duplicated comment.
Send the pics to `eaperez at me dot com`, I'll answer when I see them.
Yes, remove IntelMausi.kext and add a Realtek one, for your chip it is [this](https://github.com/Mieze/LucyRTL8125Ethernet).

**Comment by perez987** [comment]
@jzjz2000 

**SMBIOS data**:
- get [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) by _corpnewt_
- select 2. Select config.plist (drag and drop the file over Terminal window)
- select 3. Generate SMBIOS >> you'll see `Please type the SMBIOS to gen (i.e. iMac18,3)`
- write `iMac20,2` and press ENTER
- GenSMBIOS updates config.plist with the new values, you must have filled 4 keys: MLB, ROM, SystemSerialNumber and SystemUUID.

**Comment by perez987** [comment]
@jzjz2000 
Ok, I already got the folder `original install config igpu not working`. I made changes on it:

- `AAPL,ig-platform-id = 0300913E` (was `07009B3E`)
- remove SATA Hot plug patch (avoid errors with not necessary stuff)
- add LucyRTL8125Ethernet.kext in config.plist (don't forget to add it also in the Kexts folder)
- remove Windows entry (avoid errors with not necessary stuff)
- `PlatformInfo > Generic > ProcessorType` changed to 0 (was 4105), 0 forces OpenCore to detect the CPU family
- `PlatformInfo > Generic > ROM` = 20768F7DD5F9 (was empty).

We must be clear about the way to introduce the values in config.plist:

- as hexadecimal if doing on PlistPro Editor

<img width="544" alt="plist-editor" src="https://user-images.githubusercontent.com/50429399/224569057-9168bfda-3a6d-433a-838b-3f1b78ccf17a.png">

- as Base64 if doing it on a plain text editor.

```xml
	<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1F,0x3)</key>
			<dict>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>layout-id</key>
				<data>BwAAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>enable-metal</key>
				<data>AQAAAA==</data>
				<key>rps-control</key>
				<data>AQAAAA==</data>
			</dict>
			<key>PciRoot(0x0)/Pci(0x14,0x0)</key>
			<dict>
				<key>acpi-wake-gpe</key>
				<data>bQ==</data>
				<key>acpi-wake-type</key>
				<data>AQ==</data>
			</dict>
		</dict>
```

These 2 pics have the same code, hexadecimal within plist editor and Base64 as plain text.

[LucyRTL8125Ethernet.zip](https://github.com/perez987/macOS-12-13-on-Z390-with-OpenCore/files/10951883/LucyRTL8125Ethernet.zip)

[config.plist.zip](https://github.com/perez987/macOS-12-13-on-Z390-with-OpenCore/files/10951884/config.plist.zip)

**Comment by perez987** [comment]
@jzjz2000

Hackintool >> System tab
Here we must pay attention to 2 items:
- `Intel Generation ???` >> the iGPU is not being well detected, even not detected at all. This is normal when using iMacPro1,1, (iGPU disabled in BIOS) but not with iMac20,2. Try the `AAPL,ig-platform-id` I posted above
- `VDA Decoder = Decoder Failed` >> you are be able to encode or decode video by hardware only when you see here `Fully Supported`.

I recommend to try `AAPL,ig-platform-id= 0300913E` to see if Intel generation and VDA Decoder are fixed.

In case of error, it's worth to try iMacPro1,1 (iGPU disabled in BIOS and no code for it in config.plist), it's the SMBIOS I use since a lot of time ago and I think the system runs very fine so.
