### ISSUE TITLE
Everything is working fine except Fenvi FV-T919 BCM94360CD bluetooth

### ISSUE THREAD

**Issue by thefreequest** [perez987/macOS-12-13-on-Z390-with-OpenCore#4]
Thanks for your hard Work. Everything is working fine except Fenvi FV-T919 BCM94360CD bluetooth, in MacOs Monterey works fine both bluetooth and Wifi. Now only, after upgrading to Ventura, Wifi is working fine. Bluetooth is detected, but cannot activate it via the interface. Actually working with your config-13-imacpro.plist: iMacPro1,1 + dGPU AMD + iGPU disabled in BIOS.

System reports:
  Bluetooth Controller:
  Address:	NULL
  State:	Off
  Chipset:	BCM_4350C2
  Discoverable:	Off
  Firmware Version:	v0 c0
  Supported Devices:	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT SerialPort >
  Transport:	UART
  Vendor ID:	0x004C (Apple)

Hackingtool detectected this
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/RP04@1C,3/IOPP/ARPT@0
PciRoot(0x0)/Pci(0x1C,0x3)/Pci(0x0,0x0)

Hackingtool USB Port Mapping

![Screenshot 2023-03-17 at 14 22 34](https://user-images.githubusercontent.com/7127044/225917052-e4d267d8-6432-45f2-86ac-4d2e35d19008.png)

Thanks for your help

**Comment by jzjz2000** [comment]
Hi there.
I'm using this setup with a "fresh" install of Ventura. 

My Fenvi works, Wi-Fi is fine, BT works but is a little weak on the signal.

Only differences I notice between your setup comments vs. mine is:
- I did a fresh install of Ventura, not an upgrade.
- I used the config.plist that enabled dGPU and iGPU. You used dGPU but no iGPU
- You have Intel Cannon Lake cpu, I'm using a Comet Lake.

I'm sure Perez will get you squared away. He has been very helpful and my setup works perfect.

**Comment by perez987** [comment]
@thefreequest 
Sorry for the delayed answer. I have now iMacPro1,1 SMBIOS (iGPU disabled in BIOS).

I have the Fenvi T-919 working fine on Ventura as it was working on Monterey. No kext for it, stock macOS drivers.
I have in System profiler exactly the same as @jzjz2000. Obviously yours is different.

<img width="534" alt="bluetooth" src="https://user-images.githubusercontent.com/50429399/226338849-be259211-a29b-4204-b95e-c00f59a19449.png">

Is your machine a laptop? Mine is a desktop, the only required thing is to plug the Fenvi BT cable into a USB2 connector in the mobo.

I see your USB ports, you have more than 15, do you have a proper USB ports map? Your internal ports are empty, but at least one internal port has to show a USB2 hub (also seen in @jzjz2000) or the Bluetooth device connected.

<img width="621" alt="usb-ports" src="https://user-images.githubusercontent.com/50429399/226339726-4700c0c4-0911-475c-adaa-55a11b8b25d7.png">

My Hackintool >> System >> Peripherals is also the same as @jzjz2000 .

I don't know why you have the BT working on Monterey but failing on Ventura. The only idea is the well built USB port map.

**Comment by thefreequest** [comment]
﻿Thanks you for your response. I agree with you this is a USB map issue, by the way my machine is a desktop too Z390 gigabyte based. So I’ll remap the usb ports.
Thanks a lot.
Gonzalo Morales ᒡ◯ᵔ◯ᒢ

**Comment by perez987** [comment]
@thefreequest 
Gonzalo, the easiest way to map USB ports (if you have also Windows on the same PC) is USBToolBox.
https://github.com/perez987/USB-ports-map-for-macOS-with-USBToolBox

Without Windows, I think you must go to Hackintool or USBCommand.
https://perez987.es/ajuste-de-puertos-usb-en-z390-aorus-elite/ (Spanish)
https://github.com/corpnewt/USBMap

**Comment by thefreequest** [comment]
I've remapped the USB Ports using a Windows 10 install media pendrive, use repair option and then from command line, your can run the windows USBToolBox utility, and make the port thing, save to the pen drive the UTB.kext, and then in MacOs again add this to the Open Core EFI. Everything is working as previously with Monterey. Thanks a lot to you guys, to point me to the exact issue.

When finally Apple stop supporting Intel machines at all, I'll miss the Hackingtosh community.

**Comment by perez987** [comment]
@thefreequest 
Glad to read you. Enjoy.
